version: '3'
services:
    mysql-db:
      image: docker.io/mysql:latest
      container_name: mysql-db
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=FINTECH
        - MYSQL_PASSWORD=root
      ports:
        - 3306:3306